apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.1.1"
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/helm-values/kube-prometheus-stack/base.yaml
          - $values/helm-values/kube-prometheus-stack/dev.yaml
    - repoURL: https://github.com/cokee96/observability-stack
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
